### ISSUE TITLE
Honey dipped berries

### ISSUE THREAD

**Issue by gohkenytp** [purejosh/sweetberryfoods#4]
I would also like to include berries dipped in honey by crafting any type of berry and a honeycomb just to make the sweet flavor addition to Minecraft

**Comment by purejosh** [comment]
That's a great idea. I'm not sure when I'll implement it, but when I update the mod again, I'll look into doing that.

**Comment by purejosh** [comment]
Implemented in [5333ef8](https://github.com/purejosh/sweetberryfoods/commit/5333ef80a579af00a4edb939d17143a366554852).

**Comment by purejosh** [comment]
Implemented in [13c5c06](https://github.com/purejosh/sweetberryfoods/commit/13c5c06c872ee9f30ac4952fb782f6a0eb661f2c)
