### ISSUE TITLE
[Suggestion] Serene Seasons Compatibility

### ISSUE THREAD

**Issue by windth001** [purejosh/sweetberryfoods#9]
Would love to see compatibility with Serene Seasons (https://modrinth.com/mod/serene-seasons) 1.20.1+

**Comment by windth001** [comment]
Added information from Serene Season's FAQ: "By default, any crops not listed in the seasonal crop block/item tags will always be fertile. Other crop mods have to add compatibility with our block/item tags, but user-made datapacks can also be used for mods that don't have support."

**Comment by purejosh** [comment]
I've added their requested tags, and it'll be released with the next update. :) Not sure when I'll drop it, but hopefully not too long.
